/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_biletnikov_hotkeys_GlobalKeyboardHook */

#ifndef _Included_com_biletnikov_hotkeys_GlobalKeyboardHook
#define _Included_com_biletnikov_hotkeys_GlobalKeyboardHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_biletnikov_hotkeys_GlobalKeyboardHook
 * Method:    checkHotKey
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_biletnikov_hotkeys_GlobalKeyboardHook_checkHotKey
  (JNIEnv *, jobject);

/*
 * Class:     com_biletnikov_hotkeys_GlobalKeyboardHook
 * Method:    setHotKey
 * Signature: (IZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_biletnikov_hotkeys_GlobalKeyboardHook_setHotKey
  (JNIEnv *, jobject, jint, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     com_biletnikov_hotkeys_GlobalKeyboardHook
 * Method:    resetHotKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_biletnikov_hotkeys_GlobalKeyboardHook_resetHotKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
